[package]
name = "envypt-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Secure, local-first encrypted environment files"

[[bin]]
name = "envypt"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
envypt-core = { path = "../envypt-core" }
envypt-crypto = { path = "../envypt-crypto" }
envypt-output = { path = "../envypt-output" }
envypt-runtime = { path = "../envypt-runtime" }
envypt-schema = { path = "../envypt-schema" }
